# Generated by Django 5.2.10 on 2026-01-30 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Konten')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('TWITTER', 'Twitter / X'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube')], default='INSTAGRAM', max_length=20, verbose_name='Platform')),
                ('link_konten', models.URLField(max_length=500, verbose_name='Link Konten')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diinput Oleh')),
            ],
            options={
                'verbose_name': 'Konten Digital',
                'verbose_name_plural': 'Daftar Konten',
                'ordering': ['-tanggal_upload'],
            },
        ),
    ]
