# Generated by Django 4.2 on 2026-01-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TugasKonten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tugas', models.CharField(choices=[('LIKE', 'Like / Suka'), ('KOMEN', 'Komentar Positif'), ('SHARE', 'Share / Repost'), ('FOLLOW', 'Follow Akun'), ('REPLY', 'Reply / Balas Komentar'), ('ALL', 'Semua Aksi (Like, Komen, Share)')], default='LIKE', max_length=20)),
                ('instruksi', models.TextField(blank=True, help_text="Contoh: 'Komen dengan tagar #IndonesiaMaju'")),
                ('tanggal_mulai', models.DateField(verbose_name='Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Selesai')),
                ('poin', models.IntegerField(default=10, help_text='Poin untuk kader yang mengerjakan')),
                ('aktif', models.BooleanField(default=True)),
                ('konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tugas', to='konten.konten')),
            ],
            options={
                'verbose_name': 'Tugas / Misi',
                'verbose_name_plural': 'Daftar Tugas',
            },
        ),
    ]
