# Generated by Django 4.2 on 2026-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0002_tugaskonten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugaskonten',
            name='jenis_tugas',
        ),
        migrations.AddField(
            model_name='tugaskonten',
            name='is_follow',
            field=models.BooleanField(default=False, verbose_name='Follow'),
        ),
        migrations.AddField(
            model_name='tugaskonten',
            name='is_komen',
            field=models.BooleanField(default=False, verbose_name='Komentar'),
        ),
        migrations.AddField(
            model_name='tugaskonten',
            name='is_like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
        migrations.AddField(
            model_name='tugaskonten',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='Reply'),
        ),
        migrations.AddField(
            model_name='tugaskonten',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='Share'),
        ),
    ]
