# Generated by Django 4.2 on 2026-01-30 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konten', '0003_remove_tugaskonten_jenis_tugas_tugaskonten_is_follow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunMedsos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('TWITTER', 'Twitter / X'), ('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube')], default='INSTAGRAM', max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('link_profil', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akun_medsos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aset Akun Medsos',
                'verbose_name_plural': 'Daftar Aset Medsos',
            },
        ),
    ]
