# Generated by Django 4.2 on 2026-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='akunmedsos',
            name='role_pemegang',
            field=models.CharField(default='CADRE', max_length=20),
        ),
    ]
