# Generated by Django 4.2 on 2026-01-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0006_akunmedsos_role_pemegang'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='akunmedsos',
            unique_together={('platform', 'username')},
        ),
    ]
