# Generated by Django 4.2 on 2026-01-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('konten', '0007_alter_akunmedsos_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_selesai', models.DateTimeField(auto_now_add=True)),
                ('poin_didapat', models.IntegerField()),
                ('akun_digunakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konten.akunmedsos')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_masuk', to='konten.tugaskonten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_misi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Misi',
                'verbose_name_plural': 'Riwayat Misi',
                'unique_together': {('tugas', 'akun_digunakan')},
            },
        ),
    ]
