# Generated by Django 4.2 on 2026-01-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0008_riwayatmisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat_lengkap',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AddField(
            model_name='profile',
            name='biodata_lengkap',
            field=models.BooleanField(default=False, verbose_name='Biodata Sudah Lengkap'),
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to='ktp/', verbose_name='Foto KTP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='NIK (KTP)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nomor_hp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nomor HP/WA'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tanggal_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
    ]
