# Generated by Django 4.2.27 on 2026-01-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0009_profile_alamat_lengkap_profile_biodata_lengkap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='konten',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Konten'),
        ),
        migrations.AddField(
            model_name='konten',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Konten'),
        ),
    ]
