# Generated by Django 4.2.27 on 2026-01-31 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0010_konten_deskripsi_konten_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKonten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Kategori Konten',
                'verbose_name_plural': 'Master Kategori',
            },
        ),
        migrations.AlterField(
            model_name='konten',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konten.kategorikonten', verbose_name='Kategori Konten'),
        ),
    ]
