# Generated by Django 4.2 on 2026-01-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0011_kategorikonten_alter_konten_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konten',
            name='link_konten',
            field=models.URLField(max_length=500, unique=True, verbose_name='Link Konten'),
        ),
    ]
