# Generated by Django 4.2 on 2026-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0012_alter_konten_link_konten'),
    ]

    operations = [
        migrations.AddField(
            model_name='akunmedsos',
            name='catatan_dco',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan dari DCO'),
        ),
    ]
