# Generated by Django 4.2 on 2026-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0013_akunmedsos_catatan_dco'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatmisi',
            name='catatan_verifikator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='foto_bukti',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/'),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='tanggal_verifikasi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
