# Generated by Django 4.2 on 2026-01-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0014_riwayatmisi_catatan_verifikator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatmisi',
            name='bukti_follow',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/follow/'),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='bukti_komen',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/komen/'),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='bukti_like',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/like/'),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='bukti_reply',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/reply/'),
        ),
        migrations.AddField(
            model_name='riwayatmisi',
            name='bukti_share',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_misi/share/'),
        ),
    ]
